# Generated by Django 4.2.2 on 2024-02-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0002_alter_user_first_name_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='Nil', max_length=150),
        ),
    ]
