# Generated by Django 4.2.2 on 2024-02-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0003_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_service',
            field=models.BooleanField(default=False, verbose_name='Is Service Center'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_user',
            field=models.BooleanField(default=False, verbose_name='Is User'),
        ),
    ]
