# Generated by Django 4.2.2 on 2024-02-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0005_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='message',
            field=models.TextField(default='Nil', max_length=1000),
        ),
    ]
